/**
 * Event Deduplication Utilities for SQL Profiler
 * 
 * Prevents duplicate events from being captured/displayed by:
 * 1. Creating unique signatures for events
 * 2. Maintaining a time-windowed cache of recent signatures
 * 3. Filtering internal/system queries
 */

import * as crypto from 'crypto';

export interface DeduplicationConfig {
  /** Time window in milliseconds to consider events as duplicates */
  windowMs: number;
  /** Maximum signatures to keep in memory */
  maxSignatures: number;
  /** Enable internal query filtering */
  filterInternalQueries: boolean;
}

/**
 * Creates a normalized version of SQL statement for comparison
 * - Removes extra whitespace
 * - Normalizes case for consistency
 * - Removes comment lines
 */
export function normalizeSqlStatement(statement: string): string {
  if (!statement) {
    return '';
  }
  
  return statement
    .trim()
    .replace(/\s+/g, ' ') // Normalize whitespace
    .replace(/--.*$/gm, '') // Remove SQL comments
    .replace(/\/\*[\s\S]*?\*\//g, '') // Remove block comments
    .toUpperCase() // Normalize case
    .trim();
}

/**
 * Identifies if a query is an internal/system query
 * These queries are typically generated by monitoring tools, not user actions
 */
export function isInternalQuery(statement: string): boolean {
  const normalizedStmt = normalizeSqlStatement(statement);
  
  // Patterns that indicate system/internal queries
  const internalPatterns = [
    // Extended Events internals
    /SYS\.DM_XE_DATABASE_SESSION_TARGETS/,
    /SYS\.DM_XE_DATABASE_SESSIONS/,
    /SYS\.SERVER_EVENT_SESSIONS/,
    /SYS\.DM_XE_/,
    
    // Query Store internals
    /SYS\.QUERY_STORE/,
    
    // DMV/DMF queries (Data Management Views/Functions)
    /SYS\.DM_[A-Z_]+/,
    
    // Audit queries
    /SYS\.SERVER_AUDIT/,
    /SYS\.DATABASE_AUDIT/,
    
    // Azure Cosmos/Connection queries
    /INFORMATION_SCHEMA\./,
    
    // Empty statements (batch completed without real statement)
    /^\\s*$/,
  ];
  
  return internalPatterns.some(pattern => pattern.test(normalizedStmt));
}

/**
 * Creates a cryptographic signature for an event
 * Uses timestamp, normalized statement, user, and database
 * NOTE: Intentionally EXCLUDES event ID to detect exact duplicates
 * (same statement executed in parallel connections)
 */
export function createEventSignature(eventData: {
  timestamp: string;
  statement: string;
  userName?: string;
  databaseName?: string;
}): string {
  const normalized = normalizeSqlStatement(eventData.statement);
  
  // Create signature from key fields
  // Using millisecond precision but truncated to 100ms windows
  const timestampMs = new Date(eventData.timestamp).getTime();
  const timestampWindow = Math.floor(timestampMs / 100) * 100;
  
  const signatureData = [
    timestampWindow.toString(),
    normalized,
    eventData.userName || 'unknown',
    eventData.databaseName || 'unknown',
  ].join('|');
  
  return crypto
    .createHash('sha256')
    .update(signatureData)
    .digest('hex')
    .substring(0, 16); // Use first 16 chars for brevity
}

/**
 * Deduplication engine with time-windowed cache
 * 
 * Filters true duplicates (same statement, timestamp, user, database within time window)
 * but preserves legitimate parallel executions (same statement with different event IDs)
 */
export class EventDeduplicator {
  private recentSignatures: Map<string, { timestamp: number; eventIds: Set<string> }> = new Map();
  private config: DeduplicationConfig;
  
  constructor(config: Partial<DeduplicationConfig> = {}) {
    this.config = {
      windowMs: 5000, // 5 second default window
      maxSignatures: 1000,
      filterInternalQueries: true,
      ...config,
    };
  }
  
  /**
   * Check if event should be filtered (is a duplicate or internal)
   * 
   * Returns TRUE to filter (deduplicate) if:
   * 1. Statement is empty
   * 2. Statement is internal/system query
   * 3. EXACT same signature (statement+user+db+timestamp) AND same event ID seen recently
   * 
   * Returns FALSE (keep event) if:
   * 1. Different statement
   * 2. Different event ID (indicates separate execution/connection)
   * 3. Same signature but outside time window
   */
  isDuplicate(eventData: {
    timestamp: string;
    statement: string;
    userName?: string;
    databaseName?: string;
    eventName?: string;
    id?: string; // Event ID from XE (evt_123, etc)
  }): boolean {
    // Always filter empty statements
    const normalized = normalizeSqlStatement(eventData.statement);
    if (!normalized) {
      return true;
    }
    
    // Filter internal queries if enabled
    if (this.config.filterInternalQueries && isInternalQuery(eventData.statement)) {
      return true;
    }
    
    // Check for recent duplicate with SAME EVENT ID
    const signature = createEventSignature(eventData);
    const cached = this.recentSignatures.get(signature);
    
    if (cached !== undefined) {
      const now = Date.now();
      const timeSinceLastSeen = now - cached.timestamp;
      
      // Consider it a duplicate if:
      // 1. We've seen this EXACT signature recently (within window)
      // 2. AND the event ID is already in our cache (same execution)
      if (timeSinceLastSeen < this.config.windowMs) {
        const eventId = eventData.id || 'unknown';
        
        if (cached.eventIds.has(eventId)) {
          // Same event ID seen before = TRUE DUPLICATE
          return true;
        }
        
        // Different event ID but same signature = Parallel execution
        // Add this event ID to the cache for future comparisons
        cached.eventIds.add(eventId);
        return false; // Keep this event (it's a different execution)
      }
    }
    
    // First time seeing this signature
    const eventId = eventData.id || 'unknown';
    this.recentSignatures.set(signature, {
      timestamp: Date.now(),
      eventIds: new Set([eventId]),
    });
    
    // Cleanup old signatures if cache is getting too large
    if (this.recentSignatures.size > this.config.maxSignatures) {
      this.cleanupOldSignatures();
    }
    
    return false; // Keep this event
  }
  
  /**
   * Remove signatures older than the window
   */
  private cleanupOldSignatures(): void {
    const now = Date.now();
    const toDelete: string[] = [];
    
    for (const [signature, cached] of this.recentSignatures.entries()) {
      if (now - cached.timestamp > this.config.windowMs) {
        toDelete.push(signature);
      }
    }
    
    for (const signature of toDelete) {
      this.recentSignatures.delete(signature);
    }
  }
  
  /**
   * Clear all cached signatures (useful for testing or reset)
   */
  clear(): void {
    this.recentSignatures.clear();
  }
  
  /**
   * Get deduplication stats
   */
  getStats() {
    return {
      cachedSignatures: this.recentSignatures.size,
      maxSignatures: this.config.maxSignatures,
      windowMs: this.config.windowMs,
    };
  }
}

/**
 * Event type priority for selecting which event to keep when duplicates exist
 * Higher number = lower priority (more likely to be filtered)
 */
export const EVENT_TYPE_PRIORITY: Record<string, number> = {
  'sql_statement_completed': 1, // Keep these (most specific)
  'rpc_completed': 1,
  'sql_batch_completed': 2, // Filter these (less specific)
  'attention_received': 3,
  'unknown': 999,
};

/**
 * Filter events based on type priority
 * When comparing similar events at same timestamp, keep higher priority
 */
export function selectPreferredEvent(
  event1: { eventName: string; timestamp: string; statement: string },
  event2: { eventName: string; timestamp: string; statement: string }
): typeof event1 {
  const priority1 = EVENT_TYPE_PRIORITY[event1.eventName] ?? 999;
  const priority2 = EVENT_TYPE_PRIORITY[event2.eventName] ?? 999;
  
  // Lower priority number = more preferred
  return priority1 <= priority2 ? event1 : event2;
}
